[vlive]
title = "Star Board"
url = "https://vlive.tv/channel/E1F3A7/board/4386"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"
contentSelector = ".writer--pwvK2"
