[vlive]
title = "Star Board"
url = "https://vlive.tv/channel/E1F3A7/board/4386"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"
contentSelector = ".writer--pwvK2"

[vlive_post]
title = "Notice"
url = "https://vlive.tv/channel/E1F3A7/board/950"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"
contentSelector = ".writer--pwvK2"

[bbc_naverpost]
title = "Block Berry Creative ─ LOONA"
url = "https://post.naver.com/my/series/detail.nhn?seriesNo=369070&memberNo=39258591"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = ".spot_post_date"
