[vlive]
title = "Star Board"
url = "https://vlive.tv/channel/E1F3A7/board/4386"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
contentSelector = "em[class^='writer']"
waitUntil = "networkidle"

[vlive_post]
title = "Notice"
url = "https://vlive.tv/channel/E1F3A7/board/950"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "em[class^='writer']"
waitUntil = "networkidle"

[bbc_naverpost]
title = "Block Berry Creative ─ LOONA"
url = "https://post.naver.com/my/series/detail.nhn?seriesNo=369070&memberNo=39258591"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[daumcafe_notice]
title = "공지사항"
url = "https://m.cafe.daum.net/loonatheworld/F5dA"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"

[daumcafe_offline]
title = "공방공지"
url = "https://m.cafe.daum.net/loonatheworld/F6Fq"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"

[daumcafe_schedule]
title = "스케줄방"
url = "https://m.cafe.daum.net/loonatheworld/F5dC"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"

[daumcafe_official]
title = "공식자료"
url = "https://m.cafe.daum.net/loonatheworld/F5dG"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"

[daumcafe_diary]
title = "소녀 Diary"
url = "https://m.cafe.daum.net/loonatheworld/F5dr"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"

[daumcafe_loonatv]
title = "LOOΠΔ TV"
url = "https://m.cafe.daum.net/loonatheworld/GoAp"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"

[daumcafe_loonalog]
title = "LOOΠΔ LOG"
url = "https://m.cafe.daum.net/loonatheworld/IGsg"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"

[daumcafe_loonatvprequel]
title = "LOOΠΔ TV Prequel"
url = "https://m.cafe.daum.net/loonatheworld/HZtw"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"

[daumcafe_toorbit]
title = "To. Orbit"
url = "https://m.cafe.daum.net/loonatheworld/F5df"
entrySelector = "#slideArticleList > ul li"
titleSelector = "span[class='txt_detail']"
linkSelector = "a[class='link_cafe make-list-uri #article_list']"
imageSelector = "a img[class='article_thumb']"
contentSelector = "span[class='created_at']"
